NO_DATA_FILL: -9999
TMP_FOLDER: '/scratch/${USER}/temp/'
GAUGE_RETRIEVAL:
    VARIABLES : ['tre200s0','prestas0','ure200s0','rre150z0','dkl010z0','fkl010z0']
    STATIONS : 'all'
    MIN_R_HOURLY : 0.1
    MAX_NB_SLURM_JOBS: 6
    
REFERENCE_RETRIEVAL:
    PRODUCTS : ['RZC','CPCH','CPC.CV','BZC','MZC','MVRZC','MVCPCH']
    MV_METHOD: 'lucaskanade' # see https://pysteps.readthedocs.io/en/latest/generated/pysteps.motion.interface.get_method.html
    NEIGHBOURS_X : [-1,0,1] # not applied to CPC.CV
    NEIGHBOURS_Y : [-1,0,1] # not applied to CPC.CV
    MAX_NB_SLURM_JOBS: 20
    
RADAR_RETRIEVAL:
    RADARS: ['A','D']
    RADAR_VARIABLES : ['ZH','ZV','ZH_VISIB','ZV_VISIB','ZDR','KDP','RHOHV','SW','RVEL','AH','ZH_CORR','ZV_CORR','ZDR_CORR','VISIB','NH','NV']
    COSMO_VARIABLES : []
    OTHER_VARIABLES: ['HEIGHT','VPR'] # Only at center pixel
    AGGREGATION_METHODS: ['mean'] # value at max/min of kdp for kdp and max/min of zh for all other variables
    TEMP_REF: 'ISO0_HEIGHT' # or 'TAIR'
    SWEEPS: [1,2,3,4,5]
    NEIGHBOURS_X : [0]
    NEIGHBOURS_Y : [0]
    KDP_PARAMETERS:
        RMIN : 1000.
        RMAX : 50000.
        RCELL : 1000.
        ZMIN : 20.
        ZMAX : 40.
        RWIND : 6000.
    SNR_THRESHOLD: 3
    VISIB_CORR:
        MIN_VISIB: 37
        MAX_CORR: 2
    MAX_SIMULTANEOUS_JOBS: 20
    MAX_NB_SLURM_JOBS: 100
